apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-limits
  annotations:
    policies.kyverno.io/category: "Best Practices"
    policies.kyverno.io/description: "Require CPU and memory resource limits on all containers."
    policies.kyverno.io/severity: "medium"
    policies.kyverno.io/title: "Require Resource Limits"
    pod-policies.kyverno.io/autogen-controllers: "none"
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: require-requests-and-limits
    exclude:
      any:
      - resources:
          namespaces:
          - argocd
          - kube-system
          - kyverno
          - ingress-nginx
          - falco
    match:
      any:
      - resources:
          kinds:
          - Pod
          - Deployment
          - StatefulSet
          - DaemonSet
          - ReplicaSet
    validate:
      message: "All containers must have CPU and memory requests and limits."
      pattern:
        spec:
          =(template):
            spec:
              containers:
              - resources:
                  requests:
                    memory: "?*"
                    cpu: "?*"
                  limits:
                    memory: "?*"
                    cpu: "?*"
